server:
  port: 8200

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_commerce
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 10000
      minimum-idle: 5
      connection-timeout: 15000
      pool-name: hikari-pool
      max-lifetime: 60000

  jpa:
    show-sql: true